name: marketplace
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0-134.0.dev

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  get_it: ^8.0.3

  # Routing
  go_router: ^14.8.0

  # utils
  http: ^1.3.0  
  fluttertoast: ^8.2.12
  flutter_screenutil: ^5.9.3
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/empty-image.png
    - assets/linkedin.png
    - assets/whatsapp.png
